# TCL File Generated by Component Editor 20.1
# Sat Dec 18 21:06:28 CST 2021
# DO NOT MODIFY


# 
# game_core "game_core" v1.0
# Hu Jiarun 2021.12.18.21:06:28
# Game which interface with software and hardware (64x16-bit register)
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module game_core
# 
set_module_property DESCRIPTION "Game which interface with software and hardware (64x16-bit register)"
set_module_property NAME game_core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ECE385 Custom IPs"
set_module_property AUTHOR "Hu Jiarun"
set_module_property DISPLAY_NAME game_core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_game_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file game_interface.sv SYSTEM_VERILOG PATH game_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_game_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file game_interface.sv SYSTEM_VERILOG PATH game_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point REST
# 
add_interface REST reset end
set_interface_property REST associatedClock CLK
set_interface_property REST synchronousEdges DEASSERT
set_interface_property REST ENABLED true
set_interface_property REST EXPORT_OF ""
set_interface_property REST PORT_NAME_MAP ""
set_interface_property REST CMSIS_SVD_VARIABLES ""
set_interface_property REST SVD_ADDRESS_GROUP ""

add_interface_port REST RESET reset Input 1


# 
# connection point GAME_Slave
# 
add_interface GAME_Slave avalon end
set_interface_property GAME_Slave addressUnits WORDS
set_interface_property GAME_Slave associatedClock CLK
set_interface_property GAME_Slave associatedReset REST
set_interface_property GAME_Slave bitsPerSymbol 8
set_interface_property GAME_Slave burstOnBurstBoundariesOnly false
set_interface_property GAME_Slave burstcountUnits WORDS
set_interface_property GAME_Slave explicitAddressSpan 0
set_interface_property GAME_Slave holdTime 0
set_interface_property GAME_Slave linewrapBursts false
set_interface_property GAME_Slave maximumPendingReadTransactions 0
set_interface_property GAME_Slave maximumPendingWriteTransactions 0
set_interface_property GAME_Slave readLatency 0
set_interface_property GAME_Slave readWaitTime 1
set_interface_property GAME_Slave setupTime 0
set_interface_property GAME_Slave timingUnits Cycles
set_interface_property GAME_Slave writeWaitTime 0
set_interface_property GAME_Slave ENABLED true
set_interface_property GAME_Slave EXPORT_OF ""
set_interface_property GAME_Slave PORT_NAME_MAP ""
set_interface_property GAME_Slave CMSIS_SVD_VARIABLES ""
set_interface_property GAME_Slave SVD_ADDRESS_GROUP ""

add_interface_port GAME_Slave AVL_ADDR address Input 6
add_interface_port GAME_Slave AVL_BYTE_EN byteenable Input 4
add_interface_port GAME_Slave AVL_CS chipselect Input 1
add_interface_port GAME_Slave AVL_READ read Input 1
add_interface_port GAME_Slave AVL_READDATA readdata Output 32
add_interface_port GAME_Slave AVL_WRITE write Input 1
add_interface_port GAME_Slave AVL_WRITEDATA writedata Input 32
set_interface_assignment GAME_Slave embeddedsw.configuration.isFlash 0
set_interface_assignment GAME_Slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment GAME_Slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment GAME_Slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock CLK
set_interface_property conduit_end associatedReset REST
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end EXPORT_DATA readdata Output 2048

